name: Deploy_HTML
# Only trigger, when the validation workflow succeeded
on:
  workflow_run:
    workflows: ["ci_validation"]
    branches:
      - main
    types:
     - completed
   # paths:
   #   - 'notebooks/**.ipynb'
   
jobs:
  HTMLBuilder:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/ci_builder.yml@hellouniverse
