name: ci_validation 

on:
  push:
    branches:
    - main
    paths:
      - 'notebooks/**.ipynb'
env: 
  WEBBPSF_PATH: $HOME/data/webbpsf-data
  
jobs:
  NotebookExecutionValidation:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/ci_validation.yml@hellouniverse
